# Generated by Django 3.2.3 on 2021-09-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='employment_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='employment_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='employment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='employment_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='employment_seniority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
